SOLID-KATA: TASK-LIST
arifa11111/task-list_solidKata pull request #2
Opened 2023-03-06 09:31 UTC by arifa11111

### Refactor the code and implement features

#### Task-List

https://kata-log.rocks/task-list-kata

2023-03-09 05:59 UTC, AbhilashZemoso commented on .idea/.gitignore
> +/workspace.xml
add .idea folder

2023-03-09 06:00 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/Add.java
> +        public void add(String commandLine, Map<String, List<Task>> tasks, PrintWriter out) {
add an interface 
and have class fields for tasks and out fields

2023-03-09 06:00 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/AddDeadline.java
> +        String[] subcommandRest = commandLine.split(" ", 2);
add an interface 
and have class fields for tasks and out fields

2023-03-09 06:01 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/DeleteInterface.java
> +public interface DeleteInterface {
do not suffix it with Interface or I letter
rename it

2023-03-09 06:02 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/AddDelete.java
> +public class AddDelete  implements DeleteInterface{
We are not adding anything here, we are just deleting
Rename AddDelete to better name

2023-03-09 06:02 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/AddDelete.java
> +    public void delete(Map<String, List<Task>> tasks, String idString, PrintWriter out) {
have class fields for tasks and out fields

2023-03-09 06:03 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/AddProject.java
> +    public void add(Map<String, List<Task>> tasks, String project, PrintWriter out) {
have class fields for tasks and out fields

2023-03-09 06:03 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/AddTask.java
> +    public void addTask(String project, String description, Map<String, List<Task>> tasks) {
add an interface
and have class fields for tasks

2023-03-09 06:04 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/Check.java
> +    }
method is empty
make sure the functionality is still working fine

2023-03-09 06:04 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/Check.java
> +    public void check(Map<String, List<Task>> tasks, String idString, PrintWriter out) {
add an interface
and have class fields for tasks and out fields

2023-03-09 06:16 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/Uncheck.java
> +    }
according to Interface Segregation principle we should not force a class to implement a method which is not functional
Either merge Check and Uncheck classes 
or segregate interface

2023-03-09 06:17 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/CheckOrUncheckService.java
> +    }
if possible remove default method and have this as private method or in utility 
as this will cause ambiguity in future

2023-03-09 06:18 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/Execute.java
> +    public void execute(String commandLine, PrintWriter out, Map<String, List<Task>> tasks) {
add an interface
and have class fields for tasks and out fields

2023-03-09 06:19 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/Execute.java
> +                break;
do not create instances 
Have them created in constructor and use them

2023-03-09 06:19 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/Help.java
> +    public void help(PrintWriter out) {
add an interface
and have class fields for  out field

2023-03-09 06:20 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/Runner.java
> +    public void run(PrintWriter out, String QUIT, BufferedReader in, Map<String, List<Task>> tasks) {
add Runable interface
and have class fields for tasks, in and out fields

2023-03-09 06:20 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/Show.java
> +    public void show(Map<String, List<Task>> tasks, PrintWriter out) {
have class fields for tasks and out fields

2023-03-09 06:21 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/Today.java
> +public class Today implements ShowService {
rename Today class name to proper one

2023-03-09 06:21 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/Today.java
> +    public void show(Map<String, List<Task>> tasks, PrintWriter out) {
have class fields for tasks and out fields

2023-03-09 06:21 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/Uncheck.java
> +public class Uncheck implements CheckOrUncheckService{
have class fields for tasks and out fields

2023-03-09 06:21 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/ViewByDeadline.java
> +    public void show(Map<String, List<Task>> tasks, PrintWriter out) {
have class fields for tasks and out fields

2023-03-09 06:22 UTC, AbhilashZemoso requested changes
work on comments

2023-03-12 07:22 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/Execute.java
> +    ErrorHandler errorHandler;
type should be of respective implemented interfaces(ex: UpdateTaskService instead of Check ), so that we depend on abstraction than on concrete class

2023-03-12 07:23 UTC, AbhilashZemoso commented on java/src/main/java/com/codurance/training/tasks/Runner.java
> -}
don't remove this class, instead implement Runnable interface to this class

2023-03-12 07:26 UTC, AbhilashZemoso requested changes
work on comments
Make sure all tests pass

All tests are working fine
![Screenshot from 2023-03-13 13-12-09](https://user-images.githubusercontent.com/101788554/224638078-a10d99bc-0844-4f49-9d08-573563a929f1.png)

2023-03-13 07:46 UTC, arifa11111 commented
> work on comments Make sure all tests pass

All tests are working fine
![Screenshot from 2023-03-13 13-12-09](https://user-images.githubusercontent.com/101788554/224638078-a10d99bc-0844-4f49-9d08-573563a929f1.png)

2023-03-14 05:23 UTC, AbhilashZemoso approved these changes
LGTM

2023-03-14 09:28 UTC, merged